export const ERROR = 'Failed to fetch data'

export const FETCH_POKEMON_BY_KEY_REQUESTED = 'FETCH_POKEMON_BY_KEY_REQUESTED'
export const FETCH_POKEMON_BY_KEY_SUCCESSFUL = 'FETCH_POKEMON_BY_KEY_SUCCESSFUL'
export const FETCH_POKEMON_BY_KEY_FAILED = 'FETCH_POKEMON_BY_KEY_FAILED'

export const FETCH_POKEMONS_REQUESTED = 'FETCH_POKEMONS_REQUESTED'
export const FETCH_POKEMONS_SUCCESSFUL = 'FETCH_POKEMONS_SUCCESSFUL'
export const FETCH_POKEMONS_FAILED = 'FETCH_POKEMONS_FAILED'
